services:
  postgres:
    image: postgres:latest
    container_name: photobank-postgres
    environment:
      POSTGRES_USER: photobank
      POSTGRES_PASSWORD: photobank
      POSTGRES_DB: photobank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@photobank.xyz
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres-data:
  pgadmin-data:
