name: Deploy Nest App on VPS

on:
  push:
    branches:
      - master

env:
  APP_NAME: "photobank-nest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            source ~/.bashrc
            cd /var/www/photobank.patrykb.pl/backend
            git pull origin master
            pnpm install
            pnpm build
            pm2 restart ${{ env.APP_NAME }} || pm2 start dist/main.js --name "${{ env.APP_NAME }}"
            
            
            
          
